### PR TITLE
add test cases for group function in backend

### LINKED ISSUE #30: Add tests for the feature of group expense and fix the potential bug
since we add group function to the backend, I add some test cases for this. and I found and fix some logical bugs in it:

- when adding expenses to a group, the backend doesn't check if the user belong to the group.
- when get the group expenses, the backend does not check the validity of some parameters (limit and skip)

### PR DESCRIPTION
**Pull request by TheFatBlue**
since we add group function to the backend, I add some test cases for this. and I found and fix some logical bugs in it:
- when adding expenses to a group, the backend doesn't check if the user belong to the group.
- when get the group expenses, the backend does not check the validity of some parameters (`limit` and `skip`)

### CODE REVIEW

**Comment by TheFatBlue** [comment]
@TomasAndersonFang I add some test cases for backend and add some check step to it. please review them :)

**Comment by TomasAndersonFang** [comment]
It seems when you added new tests, you found some potential bugs. Could you explain what happened and introduce the bug, then show how to fix the bug?

**Review by TomasAndersonFang — APPROVED** [review]
Thanks for your enhancement and new tests, which dramatically improve the quality of our software!

**Comment by TheFatBlue** [comment]
> It seems when you added new tests, you found some potential bugs. Could you explain what happened and introduce the bug, then show how to fix the bug?

Sure, let's talk about it more specifically.

Originally, there are three failing cases (I'll post detailed error information below):
- `test_api_create_group_expenses.py::TestGroupExpenses::test_create_expense_non_member`
- `test_api_read_group_expenses.py::TestGetGroupExpenses::test_get_expenses_negative_limit`
- `test_api_read_group_expenses.py::TestGetGroupExpenses::test_get_expenses_negative_skip`

For the first one, the reason is that the function `create_group_expense` didn't check if the user creating the expense belongs to the group. I fixed this by add this checking logic:
```python
def create_group_expense(db: Session, group_id: int, expense: schemas.GroupExpenseCreate, paid_by: int):
    # code looking up group
    is_member = db.query(models.GroupMember).filter(
        models.GroupMember.group_id == group.id,
        models.GroupMember.user_id == paid_by
    ).first()
    if not is_member:
        raise HTTPException(status_code=403, detail="Not a member of this group")
```

For the last two, the reason is that the function `get_group_expenses` didn't check the validity of the parameters `limit` and `skip`. I fixed this by add following check:
```python
if skip < 0:
    raise HTTPException(
        status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
        detail="Skip value cannot be negative"
    )
if limit < 0:
    raise HTTPException(
        status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
        detail="Limit value cannot be negative"
    )
```

Below is the detailed error information for the failing test cases:
```
_____________________________________________________________________________ TestGroupExpenses.test_create_expense_non_member ______________________________________________________________________________

self = <tests.test_api_create_group_expenses.TestGroupExpenses object at 0x10652c6d0>
auth_headers_list = [{'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0X2dyb3VwX2V4cGVuc2VfMF8xNzMyNTk4OTkyLj...tcGxlLmNvbSIsImV4cCI6MTczMjYwMDc5NH0.Dnd9xzdbrZBsLZRz9q9r22k8tehiwD2-wqLPHzOT3l0', 'Content-Type': 'application/json'}]
created_group = {'created_at': '2024-11-26T05:29:54.019116', 'created_by': 373, 'id': 101, 'name': 'Test Expense Group 1732598994.0173929'}
valid_equal_split_expense = {'amount': 300.0, 'category': 'Groceries', 'date': '2024-11-26T05:29:54.025681+00:00', 'description': 'Weekly groceries', ...}
test_users = [{'email': 'test_group_expense_0_1732598992.670772@example.com', 'full_name': 'Test Group Expense User 0', 'password':...oup_expense_2_1732598992.670775@example.com', 'full_name': 'Test Group Expense User 2', 'password': 'testpassword123'}]

    def test_create_expense_non_member(
        self, auth_headers_list, created_group, valid_equal_split_expense, test_users
    ):
        """Test expense creation by non-group member"""
        # Create a new user who is not a member of the group
        new_user = {
            "email": f"non_member_{time.time()}@example.com",
            "password": "testpassword123",
            "full_name": "Non Member User"
        }
        requests.post(f"{BASE_URL}/users/", json=new_user)
        token_response = requests.post(
            f"{BASE_URL}/token",
            data={
                "username": new_user["email"],
                "password": new_user["password"]
            },
            headers={"Content-Type": "application/x-www-form-urlencoded"}
        )
        non_member_headers = {
            "Authorization": f"Bearer {token_response.json()['access_token']}",
            "Content-Type": "application/json"
        }
    
        response = requests.post(
            f"{BASE_URL}/groups/{created_group['id']}/expenses",
            json=valid_equal_split_expense,
            headers=non_member_headers
        )
>       assert response.status_code == 403
E       assert 200 == 403
E        +  where 200 = <Response [200]>.status_code

test_api_create_group_expenses.py:304: AssertionError
___________________________________________________________________________ TestGetGroupExpenses.test_get_expenses_negative_limit ___________________________________________________________________________

self = <tests.test_api_read_group_expenses.TestGetGroupExpenses object at 0x104587ac0>
auth_headers_list = [{'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0X2dldF9leHBlbnNlc18wXzE3MzI1OTkyMzEuNz...tcGxlLmNvbSIsImV4cCI6MTczMjYwMTAzM30.tcxroL_cbmoIhlNYJeOwDDQkP0EAHSIAx4kt9cPFYIg', 'Content-Type': 'application/json'}]
group_with_expenses = {'created_at': '2024-11-26T05:33:53.084413', 'created_by': 396, 'id': 107, 'name': 'Test Get Expenses Group 1732599233.082772'}

    def test_get_expenses_negative_limit(self, auth_headers_list, group_with_expenses):
        """Test reading expenses with negative limit"""
        response = requests.get(
            f"{BASE_URL}/groups/{group_with_expenses['id']}/expenses/?limit=-1",
            headers=auth_headers_list[0]
        )
>       assert response.status_code == 422
E       assert 200 == 422
E        +  where 200 = <Response [200]>.status_code

test_api_read_group_expenses.py:256: AssertionError
___________________________________________________________________________ TestGetGroupExpenses.test_get_expenses_negative_skip ____________________________________________________________________________

self = <tests.test_api_read_group_expenses.TestGetGroupExpenses object at 0x104586f80>
auth_headers_list = [{'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0X2dldF9leHBlbnNlc18wXzE3MzI1OTkyMzMuMT...1wbGUuY29tIiwiZXhwIjoxNzMyNjAxMDM0fQ.0385FjNBMuRvjVQxmW1XrsR6xjbxNTpvSLu50Bf8u2U', 'Content-Type': 'application/json'}]
group_with_expenses = {'created_at': '2024-11-26T05:33:54.475022', 'created_by': 399, 'id': 108, 'name': 'Test Get Expenses Group 1732599234.472963'}

    def test_get_expenses_negative_skip(self, auth_headers_list, group_with_expenses):
        """Test reading expenses with negative skip"""
        response = requests.get(
            f"{BASE_URL}/groups/{group_with_expenses['id']}/expenses/?skip=-1",
            headers=auth_headers_list[0]
        )
>       assert response.status_code == 422  # Validation error
E       assert 200 == 422
E        +  where 200 = <Response [200]>.status_code

test_api_read_group_expenses.py:264: AssertionError
```

**Pull request merged**
