### PR TITLE
Extra test case for the login

### PR DESCRIPTION
**Pull request by IMYXR**
#40 Already added it.

### CODE REVIEW

**Comment by TomasAndersonFang** [comment]
@IMYXR For your test
```
def test_token_with_numeric_password(self, client, test_user):
        """Test token generation with a purely numeric password"""
        test_user["password"] = "12345678"
        response = client.post(
            "/token",
            data={
                "username": test_user["email"],
                "password": test_user["password"],
                "grant_type": "password"
            },
            headers={"Content-Type": "application/x-www-form-urlencoded"}
        )
        assert response.status_code in (200, 401)
```

Could you tell me why the response status will be 200 or 401? I understand why it will be 200, but I'm confused about 401.

**Comment by TomasAndersonFang** [comment]
Moreover, it seems `test_token_with_missing_grant_type_parameter` and `test_token_with_blank_grant_type` address the same scenario, could you make sure?

**Comment by IMYXR** [comment]
> @IMYXR For your test
> 
> ```
> def test_token_with_numeric_password(self, client, test_user):
>         """Test token generation with a purely numeric password"""
>         test_user["password"] = "12345678"
>         response = client.post(
>             "/token",
>             data={
>                 "username": test_user["email"],
>                 "password": test_user["password"],
>                 "grant_type": "password"
>             },
>             headers={"Content-Type": "application/x-www-form-urlencoded"}
>         )
>         assert response.status_code in (200, 401)
> ```
> 
> Could you tell me why the response status will be 200 or 401? I understand why it will be 200, but I'm confused about 401.

The response status could be 401 (Unauthorized) because the server failed to authenticate the provided credentials or encountered issues with the authentication process. This could happen if the username or password does not match an existing user in the database, if the server enforces stricter password policies that disallow purely numeric passwords, or if there are configuration issues with the token generation process. Additionally, other factors like unsupported grant_type, rate-limiting mechanisms, or missing test data in a mock environment could also lead to authentication failure and a 401 response.

**Comment by IMYXR** [comment]
> Moreover, it seems `test_token_with_missing_grant_type_parameter` and `test_token_with_blank_grant_type` address the same scenario, could you make sure?

I have check and update it

**Pull request merged**
